FROM alpine:latest

# Install required packages
RUN apk add --no-cache build-base autoconf automake pkgconf libtool libusb libusb-dev libftdi1 libftdi1-dev git mc meson gettext-dev avrdude linux-headers texinfo make gcc-avr avr-libc cmake ca-certificates