#!/usr/bin/env bash
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
# Run the clang static analyzer over the firmware sources.
# Copyright 2024 - Nicolaus Starke
# SPDX-License-Identifier: MIT
#
# https://github.com/nic-starke/neon_samurai
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$repo_root"

target="${1:-src}"

# project.h is generated by CMake from the version in CMakeLists.txt, so the
# firmware has to have been configured at least once before this can run.
generated=""
for candidate in build/Release/generated build/RelWithDebInfo/generated \
                 build/Debug/generated build/generated; do
  if [ -f "$candidate/system/project.h" ]; then
    generated="$candidate"
    break
  fi
done

if [ -z "$generated" ]; then
  echo "error: generated headers not found - configure the firmware first:" >&2
  echo "  cmake -S . -B build/Release -DCMAKE_BUILD_TYPE=Release" >&2
  exit 1
fi

lufa="build/_deps/lufa-src"
if [ ! -d "$lufa" ]; then
  echo "error: LUFA sources not found at $lufa - configure the firmware first" >&2
  exit 1
fi

flags=(
  --analyze
  --target=avr
  -mmcu=atxmega128a4u
  -D__AVR_XMEGA__

  # See tools/analysis/README.md for why these come before the real headers.
  -I tools/analysis/shim
  -isystem /usr/avr/include

  -DARCH=ARCH_XMEGA
  -DATXMEGA128A4U
  -DBOARD=USER_BOARD
  -DF_CPU=32000000UL
  -DF_USB=48000000UL
  -DUSE_LUFA_CONFIG_HEADER=1
  -DNDEBUG

  -I src/include
  -I src/include/usb
  -I "$generated"
  -isystem "$lufa"

  -std=gnu11

  # Every memory-mapped peripheral register is a fixed address, so this check
  # fires on correct hardware access and reports nothing useful here.
  -Xclang -analyzer-disable-checker -Xclang core.FixedAddressDereference
)

status=0
files=0
findings=0

while IFS= read -r file; do
  files=$((files + 1))
  if ! output=$(clang "${flags[@]}" "$file" -o /dev/null 2>&1); then
    status=1
  fi
  if [ -n "$output" ]; then
    count=$(grep -c -E 'warning:|error:' <<<"$output" || true)
    if [ "$count" -gt 0 ]; then
      findings=$((findings + count))
      status=1
      echo "$output"
    fi
  fi
done < <(find "$target" -name '*.c' | sort)

echo "analysed $files file(s), $findings finding(s)"
exit $status
